### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by philred** [mjordan/islandora_scg#11]
Attempting to `drush en islandora_scg` on Islandora 7.x-1.5 gives me the following error:

`
PHP Fatal error:  Can't use function return value in write context in /var/www/drupal/htdocs/sites/all/modules/islandora_scg/islandora_scg.drush.inc on line 109
Drush command terminated abnormally due to an unrecoverable error.               [error]
Error: Can't use function return value in write context in
/var/www/drupal/htdocs/sites/all/modules/islandora_scg/islandora_scg.drush.inc,
line 109
`

**Comment by mjordan** [comment]
Hi @philred, I'm sorry I missed this issue.

I've pushed a fix to the 7.x branch. Can you do a `git pull` and try again? If the collection you are loading into does not exist or is not accessible to the user you are running the drush script as, you should get an error. I advise running drush with the --user=1 option to avoid permission issues.

**Comment by philred** [comment]
That worked using both `drush en islandora_scg` and `drush -u 1 en islandora_scg`. Thanks!
