### ISSUE TITLE
Support both Drush 6.x and 7.x

### ISSUE THREAD

**Issue by lo5an** [mjordan/islandora_scg#16]
[Hard coded `http://localhost`](https://github.com/mjordan/islandora_scg/search?utf8=%E2%9C%93&q=http%3A%2F%2Flocalhost&type=) URIs break imports that rely on Islandora batch commands for SSL-only installs with error:

```
The drush command 'islandora_batch_scan_preprocess' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new extensions.        [error]
Drush was not able to start (bootstrap) the Drupal database.                                                                                                                       [error]
Hint: This may occur when Drush is trying to:
 * bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the
URI to use with the --uri parameter on the command line. See `drush topic docs-aliases` for details.
 * connect the database through a socket. The socket file may be wrong or the php-cli may have no access to it in a jailed shell. See http://drupal.org/node/1428638 for details.
```

**Comment by mjordan** [comment]
@lo5an thanks for catching this. It should be no problem to allow the `--uri` parameter in `islandora_scg_load` and if present to grab its value to pass into the Islandora Batch drush job. PR is welcome but if you don't have time I can code this up. I'll ask you to test, however, since I don't have access to any multisite instances, or to any SSL-only installs.

**Comment by lo5an** [comment]
I'm happy to put a PR together, but it'll probably be a week or so before I can circle back to it.

**Comment by mjordan** [comment]
Great, thanks!

**Comment by lo5an** [comment]
It looks like I was wrong about the issue. 

I had some time to dive in his afternoon and it looks like the problem stems from the `--target` option in the batch commands beginning to conflict with the `--target`  option for some of the build-in Drush commands as of  Drush 7.x.  See [ISLANDORA-1579](https://jira.duraspace.org/browse/ISLANDORA-1579) and [this Drush ticket](https://github.com/drush-ops/drush/issues/1905) for discussion.

The new parameter `--scan_target` was added to the batch commands in Islandora 7.x-1.7 and switching to that with [this commit](https://github.com/lo5an/islandora_scg/commit/26b3faa4f6386a2f886c62f6670e364d42c096f2) seems to make things work for me. However, that doesn't account for folks using Islandora 7.x-1.6 (or older) with Drush 6.x. 

I've got to wrap up for now, but I'll find some time to do a bit more testing add in a version check.

**Comment by mjordan** [comment]
Doh! Yes, that makes total sense.

**Comment by g7morris** [comment]
@lo5an Thanks for all the work and review on this. I'm currently using your forked version with the patches and it works beautifully. Generating image and pdf samples like a boss! Hopefully you can PR soon! @mjordan Love this tool! Thanks for making it.

**Comment by mjordan** [comment]
Great, thanks @g7morris for testing. @lo5an I can merge a PR whenever you're ready.

@g7morris glad you find it useful!

**Comment by lo5an** [comment]
It looks like I should have some time to return to this later in the week.  I'll add a version check so that I don't break things for people using old Islandora with old Drush and then submit a PR.

**Comment by mjordan** [comment]
@lo5an I updated the title to more accurately describe the issue. The `--uri` issue already had a ticket, #14.

**Comment by mjordan** [comment]
@lo5an I'm in here doing a bunch of stuff so if you want me to work on this issue, no problem.

**Comment by lo5an** [comment]
It's up to you. I still have this on my list to get back to, but I'm a bit swamped at the moment.

**Comment by mjordan** [comment]
How about I implement it and you can test when you have time?

**Comment by lo5an** [comment]
Works for me :-)

**Comment by mjordan** [comment]
@lo5an I've added a check for drush verion 7 or higher. Can you test the issue-16 branch when you get some time?

**Comment by lo5an** [comment]
Sure!

**Comment by mjordan** [comment]
@lo5an can I merge the issue-16 branch? I've tested it on a machine running 6.3.0 with no ill side effects.

**Comment by lo5an** [comment]
Sorry I didn't get back to this sooner, it's been a crazy summer.  I just tested with our environment using Drush 7.4.0 and Islandora 7.x-1.7 and the issue-16 branch I got successful book imports.

**Comment by mjordan** [comment]
Sweet, thanks. If you can run it on Drush 7 and I can run it on Drush 6, I'll merge and close this issue. Thanks again!

**Comment by mjordan** [comment]
Merged into 7.x with a4ee3808070ef8856b5b585bad37413366f26249.
