### ISSUE TITLE
Not working for newspapers?

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_scg#24]
I tried generating a Newspaper with 15 issues, using the following command:

`drush iscgl -u 1 --content_model=islandora:newspaperCModel --parent=islandora:newspaper_collection --quantity=1 --pages=4 --quantity_newspaper_issues=15`

Output: 
```
Starting to generate sample content...
Generating sample content for Nelson Café
Starting to load sample content...
SetId: 2                                                             [ok]
Loading 15 issues into each newspaper.
```

But the result in my site is an empty newspaper:

![Screen Shot 2021-03-12 at 10 25 20 AM](https://user-images.githubusercontent.com/6069170/110960945-43388580-831d-11eb-8c7b-f645187243e5.png)

I don't believe the Issue objects were generated at all: the "Nelson Café" sample newspaper got the PID islandora:54, and islandora:55 doesn't exist. Object islandora:53 is one of the already-existing objects in the repository.

Something wrong with the command, or something wrong with the newspaper issue generating function?

**Comment by bondjimbond** [comment]
Batch queue also empty by the way.

**Comment by mjordan** [comment]
`drush iscgl --user=admin --quantity=2 --content_model=islandora:newspaperCModel --parent=islandora:newspaper_collection --namespace=issue24 --quantity_newspaper_issues=4` worked for me:

![image](https://user-images.githubusercontent.com/403918/111090006-513c0100-84eb-11eb-9e74-5561b5ba7045.png)

Can you copy and paste that and try it?

**Comment by bondjimbond** [comment]
Ah, I found the problem: I was using Diego's branch of Islandora Batch in order to support some features of Islandora Multi-Importer. I guess that branch is missing some code that enables this functionality. Sigh.

Thanks for testing and confirming that the problem was on my end.
